defaults: &defaults
  hamming_threshold: 12
  twitter:
    consumer_key: 
    consumer_secret: 
    oauth_token: 
    oauth_token_secret: 

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults