source 'https://rubygems.org'

gem 'rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'haml-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'haml'
gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'mongoid'
gem 'bson_ext'
gem 'symbolize', :require =>'symbolize/mongoid'
gem 'devise'
gem 'execjs'
gem 'therubyracer', :require => 'v8'
gem 'phashion'
gem 'carrierwave'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'rmagick'
gem 'quiet_assets'
gem 'redis'
gem 'settingslogic'
gem 'twitter'
gem 'resque'
gem 'resque-scheduler', '~> 2.0.0.h', :require => 'resque_scheduler'

group :development do
  gem 'standup'
end
